package de.fhswf.forms;

import de.fhswf.classes.*;
import java.awt.Color;
import javax.swing.JFrame;

public class FahrzeugWindow extends javax.swing.JFrame
{

	PrototypWindow parent;

        /** Creates new form FahrerWindow */
	public FahrzeugWindow(PrototypWindow _parent)
	{
		initComponents();
		parent = _parent;
	}

	/** Creates new form FahrerWindow */
	public FahrzeugWindow()
	{
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        txtKennzeichen = new javax.swing.JTextField();
        txtErstzulassung = new javax.swing.JTextField();
        javax.swing.JButton btnCancel = new javax.swing.JButton();
        javax.swing.JButton btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Kennzeichen");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Erstzulassung");
        jLabel3.setName("jLabel3"); // NOI18N

        txtKennzeichen.setName("txtKennzeichen"); // NOI18N
        txtKennzeichen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKennzeichenKeyTyped(evt);
            }
        });

        txtErstzulassung.setName("txtErstzulassung"); // NOI18N
        txtErstzulassung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtErstzulassungKeyTyped(evt);
            }
        });

        btnCancel.setText("Abbrechen");
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.setName("btnOk"); // NOI18N
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtErstzulassung, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(txtKennzeichen, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKennzeichen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtErstzulassung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOk))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOkActionPerformed
    {//GEN-HEADEREND:event_btnOkActionPerformed
        if (!txtKennzeichen.getText().equals("") && !txtErstzulassung.getText().equals("") && txtKennzeichen.getText().matches("^[A-Z]{1,3}-[A-Z]{1,2}-[0-9]{1,4}$") && txtErstzulassung.getText().matches("^[0-9]{1,4}$"))
        {
            dataP d = new dataP();
            Fahrzeug f = new Fahrzeug(txtKennzeichen.getText(), txtErstzulassung.getText());
            d.saveNewFahrzeug(f);
            
            parent.update();
            this.dispose();
        }
        else
        {
            
            Color lightred = new Color(255,102,102);
            
            if (txtKennzeichen.getText().equals("") || !txtKennzeichen.getText().matches("^[A-Z]{1,3}-[A-Z]{1,2}-[0-9]{1,4}$"))
            {
                txtKennzeichen.setBackground(lightred);
            }
            
            if (txtErstzulassung.getText().equals("") || !txtErstzulassung.getText().matches("^[0-9]{1,4}$"))
            {
                txtErstzulassung.setBackground(lightred);
            }
        }
    }//GEN-LAST:event_btnOkActionPerformed

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
	{//GEN-HEADEREND:event_btnCancelActionPerformed
		this.dispose();
	}//GEN-LAST:event_btnCancelActionPerformed

    private void txtKennzeichenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKennzeichenKeyTyped
        txtKennzeichen.setBackground(Color.white);
    }//GEN-LAST:event_txtKennzeichenKeyTyped

    private void txtErstzulassungKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtErstzulassungKeyTyped
        txtErstzulassung.setBackground(Color.white);
    }//GEN-LAST:event_txtErstzulassungKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField txtErstzulassung;
    javax.swing.JTextField txtKennzeichen;
    // End of variables declaration//GEN-END:variables
}
