package de.fhswf.forms;

import de.fhswf.classes.dataP;

public class PrototypWindow extends javax.swing.JFrame
{

    FahrzeugWindow fahrzeugW;
    FahrerWindow fahrerW;

    /** Creates new form PrototypWindow */
    public PrototypWindow()
    {
        initComponents();
        update();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        javax.swing.JButton btnNewFahrer = new javax.swing.JButton();
        javax.swing.JButton btnNewFahrzeug = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setName("jTable2"); // NOI18N
        jScrollPane2.setViewportView(jTable2);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        btnNewFahrer.setText("neuer Fahrer");
        btnNewFahrer.setName("btnNewFahrer"); // NOI18N
        btnNewFahrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewFahrerActionPerformed(evt);
            }
        });

        btnNewFahrzeug.setText("neues Fahrzeug");
        btnNewFahrzeug.setToolTipText("");
        btnNewFahrzeug.setName("btnNewFahrzeug"); // NOI18N
        btnNewFahrzeug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewFahrzeugActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewFahrer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNewFahrzeug))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewFahrer)
                    .addComponent(btnNewFahrzeug))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewFahrerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNewFahrerActionPerformed
    {//GEN-HEADEREND:event_btnNewFahrerActionPerformed
        if (fahrerW != null)
        {
            fahrerW.dispose();
        }
        fahrerW = new FahrerWindow(this);
        fahrerW.setVisible(true);
    }//GEN-LAST:event_btnNewFahrerActionPerformed

    private void btnNewFahrzeugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewFahrzeugActionPerformed
        if (fahrzeugW != null)
        {
            fahrzeugW.dispose();
        }
        fahrzeugW = new FahrzeugWindow(this);
        fahrzeugW.setVisible(true);
    }//GEN-LAST:event_btnNewFahrzeugActionPerformed

    public final void update()
    {
        dataP d = new dataP();
        jTable1.setModel(d.getFahrerModel());
        jTable2.setModel(d.getFahrzeugModel());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }



        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PrototypWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PrototypWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PrototypWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PrototypWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new PrototypWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTable jTable1;
    javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
